### PR TITLE
allow manager to edit his tenant details

### PR DESCRIPTION
**Pull request by mohamed-hendawy**

### CODE REVIEW

**Comment by Omranic** [comment]
Tenants are not tenantable, thus I don't think this is the right approach to allow manager to edit his tenant, rather I think it's better to add simple section with one new controller like account settings. What do you think?

**Comment by mohamed-hendawy** [comment]
Yes tenants are not tenantable but we use here the active tenant so i think there's no any problem.

**Comment by Omranic** [comment]
Check my response above / I think it's better to add simple section with one new controller like account settings. There's no need to use datatables and full CRUD to edit own tenant, feel free to reopen this PR or suit another one for a simpler solution.

**Comment by mohamed-hendawy** [comment]
where's datatables and full CRUD here ?

**Comment by Omranic** [comment]
Oh, you're right! Looks like I got confused between two different PRs. Reopened and will look into merging. Thank you

**Pull request merged**
